name: Build & Deploy to AWS (prod)

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - run: npm -g install pnpm

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build app
              run: pnpm build --mode production

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@v0.5.1
              with:
                  args: --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SOURCE_DIR: "dist"
            - name: Invalidate AWS CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
                  PATHS: /**/* /*
                  AWS_REGION: "us-east-1"
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
